name: Auto Catch Raw Data
on:
  schedule:
  - cron: '0 6,18 * * *'
  workflow_dispatch:
jobs:
  wf_getRawSkTable:
    runs-on: ubuntu-latest
    step:
    - uses: actions/checkout@v4
    - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
          architecture: 'x64'
    - name: Env
      run: pip install requests
    - name: Run
      run: python getRawSkTable.py
